tulu-3:
  prompt_template: "tulu-3-sft/prompt.txt"
  fn_completions: "huggingface_local_completions"
  completions_kwargs:
    model_name: "allenai/Llama-3.1-Tulu-3-8B-SFT"
    model_kwargs:
      torch_dtype: 'bfloat16'
    max_new_tokens: 2048
    temperature: 0.6
    top_p: 0.9
    do_sample: True
  pretty_name: "Tulu3 8B SFT"
  link: "https://huggingface.co/allenai/Llama-3.1-Tulu-3-8B-SFT"